[package]
name = "spiffe-id"
version = "0.0.0"
edition.workspace = true

[dependencies]
thiserror = { workspace = true, default-features = false }
serde = { workspace = true, default-features = false, optional = true }

[features]
default = []
serde = ["dep:serde"]
