[package]
name = "spiffe-id"
version = "0.0.0"
edition = "2021"

[dependencies]
thiserror = { version = "2.0.11", default-features = false }
serde = { version = "1.0.217", default-features = false, optional = true }

[features]
default = []
serde = ["dep:serde"]
